# Generated by Django 5.1.5 on 2025-02-02 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0019_volunteer"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologists", "Dermatologists"),
                            (
                                "Emergency Medicine Specialists",
                                "Emergency Medicine Specialists",
                            ),
                            ("Allergists/Immunologists", "Allergists/Immunologists"),
                            ("Anesthesiologists", "Anesthesiologists"),
                            ("Colon and Rectal Surgeons", "Colon and Rectal Surgeons"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.volunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologists", "Dermatologists"),
                            (
                                "Emergency Medicine Specialists",
                                "Emergency Medicine Specialists",
                            ),
                            ("Allergists/Immunologists", "Allergists/Immunologists"),
                            ("Anesthesiologists", "Anesthesiologists"),
                            ("Colon and Rectal Surgeons", "Colon and Rectal Surgeons"),
                        ],
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.volunteer",
                    ),
                ),
            ],
        ),
    ]
