# Generated by Django 4.2.18 on 2025-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0022_alter_appointment_id_alter_autodiagnosis_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="interest",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="work_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
